version: "3.2"
services: 
 mongo_db:
   image: mongo
   ports:
    - 27017:27017
   environment:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: pass1234
 mongo_express_container:
   image: mongo-express
   ports:
    - 8081:8081
   environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: admin
    ME_CONFIG_MONGODB_ADMINPASSWORD: pass1234
    ME_CONFIG_MONGODB_SERVER: mongo_db
   depends_on: 
    - "mongo_db"
