# Stage 1: Build
FROM python:3.10-slim AS build
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Verify Flask installation (this will output the installed packages)
RUN pip freeze

# Copy the rest of the application code
COPY . .

# Stage 2: Deploy
FROM python:3.10-slim
WORKDIR /app

# Copy the application code and installed dependencies from the build stage
COPY --from=build /app /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Expose port 5000 to allow access to the Flask application
EXPOSE 5000

# Run the Flask app using python -m flask
CMD ["python", "-m", "flask", "run", "--host", "0.0.0.0", "--port", "5000"]
