services:
 wordpress:
  image: wordpress:latest
  
  ports:
    - "8080:80"
  environment:
    WORDPRESS_DB_HOST: mysql:3306  
    WORDPRESS_DB_USER: root   #very importatnt to mention even it is just a default(mysql default user = root) still have to give env var for this
    WORDPRESS_DB_PASSWORD: pass1234
    WORDPRESS_DB_NAME: wordpress
  volumes:
    - wordpress-db:/var/www/html
  depends_on:
    - mysql
  restart: always


 mysql:
  image: mysql:8.0
  environment:
    MYSQL_ROOT_PASSWORD: pass1234
    MYSQL_DATABASE: wordpress
  volumes:
    - mysql-db:/var/lib/mysql

volumes:
  wordpress-db:
  mysql-db:
