FROM node AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .


FROM node:20-slim
WORKDIR /app
COPY --from=builder /app .

# Install only production dependencies
RUN npm install --only=production

EXPOSE 3000
CMD ["npm","start"]
